# Generated by Django 3.0 on 2021-05-09 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='poster_image',
            new_name='image',
        ),
    ]
